//===---*- Greatdori! -*---------------------------------------------------===//
//
// PreCache.swift
//
// This source file is part of the Greatdori! open source project
//
// Copyright (c) 2025 the Greatdori! project authors
// Licensed under Apache License v2.0
//
// See https://greatdori.memz.top/LICENSE.txt for license information
// See https://greatdori.memz.top/CONTRIBUTORS.txt for the list of Greatdori! project authors
//
//===----------------------------------------------------------------------===//

import Foundation

extension DoriCache {
    // Generated by BuildTool/PreCacheGen
    /// A built-in cache for information that updates less frequently.
    ///
    /// To make it faster to get some data which is updated less frequent,
    /// DoriKit generates a `PreCache.cache` file in **compile-time**
    /// and embeds it to `DoriKit.framework` bundle. This allows you to get some information
    /// like character list from `DoriCache.preCache` without performing a network request.
    public struct PreCache: Sendable, Hashable, Decodable {
        public var bands: [DoriAPI.Band.Band]
        public var mainBands: [DoriAPI.Band.Band]
        public var characters: [DoriAPI.Character.PreviewCharacter]
        public var birthdayCharacters: [DoriAPI.Character.BirthdayCharacter]
        public var categorizedCharacters: DoriFrontend.Character.CategorizedCharacters
        public var characterDetails: [Int: DoriAPI.Character.Character] // [CharacterID: Detail]
    }
    
    /// Get a ``PreCache``.
    @inline(never)
    public static let preCache: PreCache = {
        #if DORIKIT_ENABLE_PRECACHE
        let decoder = PropertyListDecoder()
        let result = try! decoder.decode(PreCache.self, from: Data(contentsOf: #bundle.url(forResource: "PreCache", withExtension: "cache")!))
        return result
        #else
        .init(bands: [], mainBands: [], characters: [], birthdayCharacters: [], categorizedCharacters: [:], characterDetails: [:])
        #endif
    }()
    
    /// Whether DoriKit is built with pre-cache.
    @_transparent
    public static var preCacheAvailability: Bool {
        #if DORIKIT_ENABLE_PRECACHE
        true
        #else
        false
        #endif
    }
    
    internal static func preCachedData(byID id: String) -> Any? {
        switch id {
        case "CharacterList": preCache.categorizedCharacters
        case "Home_Birthdays": preCache.birthdayCharacters
        case let x where x.hasPrefix("CharacterDetail_"):
            if let characterID = Int(String(x.dropFirst("CharacterDetail_".count))) {
                preCache.characterDetails[characterID]
            } else {
                nil
            }
        default: nil
        }
    }
}
