name: Build Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Swift
      run: |
        sudo apt -y install libcurl4-openssl-dev
        curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz && \
        tar zxf swiftly-$(uname -m).tar.gz && \
        ./swiftly init -y --overwrite --skip-install && \
        . "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh" && \
        hash -r
        swiftly install 6.2-snapshot
    - uses: actions/checkout@v4
    - name: Build
      run: swift build
