name: Build Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
      with:
        swift-version: "6.2"
    - uses: actions/checkout@v4
    - name: Build
      run: swift build
